### ISSUE TITLE
Python 3.4 import error

### ISSUE THREAD

**Issue by davidNHK** [google/python-gflags#28]
I have installed gflags on python3.4 env. 
And after i attempt import gflags it raise "No module named 'cStringIO' "

It should by changed from io import StringIO 

Possibly update look like below?

from

```

gflags/argument_parser.py 
import cStringIO
import csv
import string

```

to 

```

gflags/argument_parser.py
try: 
     from io import StringIO as cStringIO
except:
     import cStringIO#original code here
import csv
import string

```

**Comment by nickjacobson** [comment]
This pull request: https://github.com/google/python-gflags/pull/22 contains code that would fix this issue, and other Python 3 compatibility issues.

**Comment by barabo** [comment]
I'm not sure that the above fix completely solves the problem with Python 3+  It does solve the import error, but I believe there are other issues with the `argument_parser.CsvListSerializer` class (like, `unicode` doesn't exist in python3 and it's mentioned within the `Serialize` function.)
```
class CsvListSerializer(ArgumentSerializer):

  def __init__(self, list_sep):
    self.list_sep = list_sep

  def Serialize(self, value):
    """Serialize a list as a string, if possible, or as a unicode string."""
    output = cStringIO.StringIO()
    writer = csv.writer(output)

    # csv.writer doesn't accept unicode, so we convert to UTF-8.
    encoded_value = [unicode(x).encode('utf-8') for x in value]  ### <- broken in python3
    writer.writerow(encoded_value)
```

Honestly, looking at the class right above this one - I'm not sure I understand why this wouldn't work instead for either major version of python:
```
CsvListSerializer = ListSerializer
```
I say this because the `CsvListSerializer` _already_ ignores the `list_sep` argument and the ListSerializer uses the helper function to convert the list values into unicode strings.  

Unless I'm missing something, the `CsvListSerializer` class is basically useless and `ListSerializer(',')` should be used instead.

This would prevent the need to import `cStringIO` in this module entirely.

**Comment by crutcher** [comment]
Do we have any visibility on timelines here? Would additional work be welcome? I could work on py3 problems, but am unsure if they would be merged; some direction would be useful.

**Comment by gpshead** [comment]
It is actively being worked on internally, expect a push for Python 3 compatibility within a month is my best vague estimate (probably sooner but i'm not promising dates).

**Comment by sneakywombat** [comment]
@gpshead, anything we can do to help it along?

**Comment by gpshead** [comment]
We've got this working internally now; I expect @vrusinov will push the changes later this month.

**Comment by mrdrozdov** [comment]
@gpshead any followup on this?

**Comment by gpshead** [comment]
@vrusinov pushed an update and a 3.1.0 release earlier this month. give it a try.

**Comment by mrdrozdov** [comment]
This is so great! Thank you :)
